# Generated by Django 5.2.11 on 2026-03-27 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'position', 'election')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
    ]
