# Generated by Django 5.2.11 on 2026-03-27 03:47

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.election'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='receipt_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position', 'election')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election'], name='core_vote_electio_6577ff_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['position'], name='core_vote_positio_598c39_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter'], name='core_vote_voter_i_7733a7_idx'),
        ),
    ]
