# Generated by Django 5.2.11 on 2026-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vote_election_vote_ip_address_vote_receipt_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidate'], name='core_vote_candida_3799b3_idx'),
        ),
    ]
