# Generated by Django 5.2.11 on 2026-02-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voter')),
            ],
            options={
                'unique_together': {('voter', 'position', 'election')},
            },
        ),
    ]
