# Generated by Django 5.2.11 on 2026-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='phone',
        ),
        migrations.AlterField(
            model_name='voter',
            name='elections',
            field=models.ManyToManyField(blank=True, related_name='voters', to='core.election'),
        ),
    ]
