# Generated by Django 5.2.11 on 2026-03-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_voter_phone_alter_voter_elections'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
