# Generated by Django 5.2.11 on 2026-04-04 14:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_voter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
