# Generated by Django 5.2.11 on 2026-02-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
