# Generated by Django 5.2.11 on 2026-02-23 20:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
