# Generated by Django 5.2.11 on 2026-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
