# Generated by Django 5.2.11 on 2026-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactmessage_is_replied_alter_contactmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='role',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='school',
            field=models.CharField(default='Unknown School', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
